---
- name: Playbook to configure Ansible Private Automation Hub
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
    - infra.ah_configuration

  vars:
    absent_present: "{{ state | default('present') }}"

  environment:
    CONTROLLER_VERIFY_SSL: false

  pre_tasks:
    - name: "Include AAP host and credential info from vault"
      ansible.builtin.include_vars:
        file: "controller_vars/controller_vars.yml"

    - name: Get AAP version from 2.4 or older API
      ansible.builtin.uri:
        url: "https://{{ controller_host }}/api/v2/config/"
        force_basic_auth: true
        method: GET
        return_content: true
        url_password: "{{ controller_password }}"
        url_username: "{{ controller_username }}"
        validate_certs: "{{ lookup('env', 'CONTROLLER_VERIFY_SSL') | bool }}"
      register: api_version
      ignore_errors: true

    - name: Get AAP version from 2.5 or newer API
      ansible.builtin.uri:
        url: "https://{{ controller_host }}/api/controller/v2/config/"
        force_basic_auth: true
        method: GET
        return_content: true
        url_password: "{{ controller_password }}"
        url_username: "{{ controller_username }}"
        validate_certs: "{{ lookup('env', 'CONTROLLER_VERIFY_SSL') | bool }}"
      register: api_version
      ignore_errors: true

    - name: Set fact of AAP version returned from API
      ansible.builtin.set_fact:
        aap_version: "{{ api_version['json']['version'] }}"

  tasks:
    - name: Include tasks for Pre-AAP 2.5
      ansible.builtin.include_tasks:
        file: pre_aap25.yml
      when: aap_version < aap25_version

    - name: Include tasks for AAP 2.5 and newer
      ansible.builtin.include_tasks:
        file: aap25_and_newer.yml
      when: aap_version >= aap25_version
...
