---
- name: "Include hosts vars"
  include_vars: ../vars/controller_hosts.yml
  tags:
    - hosts
    - alltags

- name: "Import role to create hosts"
  import_role:
    name: redhat_cop.controller_configuration.hosts
  tags:
    - hosts
    - alltags
...
