---
- name: "Include job templates vars"
  include_vars: ../vars/controller_job_templates.yml
  tags:
    - jobtemplates
    - alltags

- name: "Import role to create job templates"
  import_role:
    name: redhat_cop.controller_configuration.job_templates
  tags:
    - jobtemplates
    - alltags
...
