---
- name: Include hosts vars
  include_vars: ../vars/controller_hosts.yml
  tags:
    - hosts
    - alltags

- import_role:
    name: redhat_cop.controller_configuration.hosts
  tags:
    - hosts
    - alltags
...
