---
- name: "Include labels vars"
  include_vars: ../vars/controller_labels.yml
  tags:
    - labels
    - alltags

- name: "Import role to create labels"
  import_role:
    name: redhat_cop.controller_configuration.labels
  tags:
    - labels
    - alltags
...
