---
- name: "Include LDAP settings vars"
  include_vars: ../vars/controller_ldap_configuration.json
  tags:
    - settings
    - alltags

- name: "Import role to configure settings"
  import_role:
    name: redhat_cop.controller_configuration.settings
  tags:
    - settings
    - alltags

- name: "Include credential types vars"
  include_vars: ../vars/controller_ldap_configuration.json
  tags:
    - settings
    - alltags

- name: "Import role to configure settings"
  import_role:
    name: redhat_cop.controller_configuration.settings
  tags:
    - settings
    - alltags
...
