---
- name: "Include projects vars"
  include_vars: ../vars/controller_projects.yml
  tags:
    - projects
    - alltags

- name: "Import role to create projects"
  import_role:
    name: redhat_cop.controller_configuration.projects
  tags:
    - projects
    - alltags
...
