---
- name: Include workflows vars
  include_vars: ../vars/controller_workflows.yml
  tags:
    - workflows
    - alltags

- import_role:
    name: redhat_cop.controller_configuration.workflow_job_templates
  tags:
    - workflows
    - alltags
...
