---
- name: "Include roles vars"
  include_vars: ../vars/controller_roles.yml
  tags:
    - roles
    - alltags

- name: "Import role to define roles (permissions)"
  import_role:
    name: redhat_cop.controller_configuration.roles
  tags:
    - roles
    - alltags
...
