---
- name: "Include credentials vars"
  include_vars: ../vars/controller_credentials.yml
  tags:
    - credentials
    - alltags

- name: "Import role to create credentials"
  import_role:
    name: redhat_cop.controller_configuration.credentials
  tags:
    - credentials
    - alltags
...
