---
- name: "Include groups vars"
  include_vars: ../vars/controller_groups.yml
  tags:
    - groups
    - alltags

- name: "Import role to create host groups"
  import_role:
    name: redhat_cop.controller_configuration.groups
  tags:
    - groups
    - alltags
...
