---
- name: "Include inventory sources vars"
  include_vars: ../vars/controller_inventory_sources.yml
  tags:
    - inventorysources
    - alltags

- name: "Import role to define inventory sources"
  include_role:
    name: redhat_cop.controller_configuration.inventory_sources
  tags:
    - inventorysources
    - alltags
...
