---
- name: "Include EE vars"
  include_vars: ../vars/controller_ees.yml
  tags:
    - ees
    - alltags

- name: "Import role to define execution environments"
  import_role:
    name: redhat_cop.controller_configuration.execution_environments
  tags:
    - ees
    - alltags
...
