---
- name: "Include credential types vars"
  include_vars: ../vars/controller_credential_types.yml
  tags:
    - credtypes
    - alltags

- name: "Import role to create credential types"
  import_role:
    name: redhat_cop.controller_configuration.credential_types
  tags:
    - credtypes
    - alltags
...
