---
- name: Include inventories vars
  include_vars: ../vars/controller_inventories.yml
  tags:
    - inventory
    - alltags

- import_role:
    name: redhat_cop.controller_configuration.inventories
  tags:
    - inventory
    - alltags
...
