---
- name: "Include teams vars"
  include_vars: ../vars/controller_teams.yml
  tags:
    - teams
    - alltags

- name: "Import role to create teams"
  import_role:
    name: redhat_cop.controller_configuration.teams
  tags:
    - teams
    - alltags
...
